import random as r

def cv(uc, cc):
    ''' A Function Takes The Input uc{User's Choice} & cc{Random Value Generated By Random Module}
		and Indentify The Outcome On The Basis Of the Outcome Matrix'''
  
    locb = [['Draw', 'Win', 'Loose'], #    Matrix For Outcomes Of The Game Where The Rows And Columns
            ['Loose', 'Draw', 'Win'], #     Represents The Outcome of Choices {0,1,2} With 
            ['Win', 'Loose', 'Draw']] #       0 = snake, 1 = water and 2 = gun
    
    res = locb[uc][cc]	#Accessing The Location Of Outcome On Basis of User And Computer's Choices	
    
    if (res == 'Win' or res == 'Loose'):
        print(f"You {res}!!!\n") 
    elif (res == 'Draw'):									
        print('Its a Draw!!\n')


def ci(x):
    if (x == 0):
        return 'Snake🐍'  
    elif (x == 1):
        return 'Water💦'  	# Function To return Strings On The Basis Of User's Choice
    elif (x == 2):
        return 'Gun🔫'


while(True):
    uc = int(input('Enter The Option You Wanna Choose\n0 for Snake🐍\t1 for Water💦\t2 for Gun🔫:\t3 for Exit\n'))
    if uc != 3:
        cc = int(r.choice(range(0, 3))) #using choice method of Random Module 

        print("User:", ci(uc), '\n')
        print("Computer:", ci(cc), '\n')

        cv(uc, cc) #Calling the Function To Identify The Outcome
    else:
        print('Thanks For Playing!!')
        break    